namespace AspireWithDapr.JiTTest.Models;

/// <summary>
/// A realistic code mutation generated by the LLM.
/// </summary>
public class Mutant
{
    /// <summary>Unique identifier, e.g. "M001".</summary>
    public string Id { get; set; } = "";

    /// <summary>Human-readable description of the mutation.</summary>
    public string Description { get; set; } = "";

    /// <summary>Why this mutation represents a plausible fault.</summary>
    public string Rationale { get; set; } = "";

    /// <summary>Relative path of the file to mutate.</summary>
    public string TargetFile { get; set; } = "";

    /// <summary>The exact original code segment being replaced.</summary>
    public string OriginalCode { get; set; } = "";

    /// <summary>The mutated replacement code.</summary>
    public string MutatedCode { get; set; } = "";

    public int LineStart { get; set; }
    public int LineEnd { get; set; }
}
